setup.ilm.enabled: false

filebeat.inputs:
  - type: log
    paths:
      - /usr/share/log/postgres.log
    multiline:
      pattern: '^[-0-9]* '
      negate: true
      match: after

output.elasticsearch:
  hosts: 
    - http://axiom-core:80/api/v1/datasets/postgres-logs/elastic
  api_key: "axiom:${PERSONAL_ACCESS_TOKEN:?You need to set the PERSONAL_ACCESS_TOKEN environment variable}"
